language: objective-c
os: osx
# xcode9: macOS Sierra 10.12, xcode7.3: OS X El Capitan 10.11
# [Building an Objective-C Project - Travis CI](https://docs.travis-ci.com/user/languages/objective-c/)
# can't be multiple definition?
#osx_image:
#  - xcode9
#  - xcode 7.3
osx_image: xcode9
# Python version is not available for OSX
# [Python runtime is not yet available on OS X · Issue #2312 · travis-ci/travis-ci](https://github.com/travis-ci/travis-ci/issues/2312)
#language: python
#python:
#  - "2.7"
#  - "3.5"
branches:
  except:
    - /^v[0-9]/
      #env:
      #  global:
      #    - GIT_COMMITTER_NAME=rcmdnk
      #    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
      #    - GIT_AUTHOR_NAME=rcmdnk
      #    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
      #    - PAGER=cat
      #    - EDITOR=cat # for brew-file edit test
      #    - VISUAL=cat
      #    - coveralls=coveralls-python
      #    #- coveralls=python-coveralls
      #  matrix:
      #    - PYTHON_VERSION="python"
      #    - PYTHON_VERSION="python3"
#install:
#  - which ruby
#  - brew install ruby
#  - hash -r
#  - which ruby
#  - which gem
script:
  - gem install rake
  - which ruby
  - which gem
  - echo $PATH
  - brew install ruby
  - hash -r
  - which ruby
  - which gem
  - export GEM_HOME=/usr/local/gems
  - export PATH=/usr/local/bin:$GEM_HOME/bin:$PATH
  - which ruby
  - which gem
  - mkdir /usr/local/gems
  - sudo mkdir /usr/local/gems
  - sudo chown travis /usr/local/gems
  - gem install ruby-prof
  - ls -l /usr
  - ls -l /usr/local
#  - gem uninstall rake
  - ./bin/brew-file brew gem install json
notifications:
  email:
    recipients:
      - rcmdnk@gmail.com
    on_success: change
    on_failure: always
